%define read_file 01
%define write_file 02
%define create_file 03
%define delete_file 04
%define create_dir 05
%define rename_file 06
%define file_exists 07
%define change_dir 8
%define delete_last_line 9
%define copy_file 10

%define print 11
%define println 12
%define clear 13
%define input 14
%define get_key 15
%define print_at 16
%define text_color 17
%define background_color 18

%define sys_exit 60
