name: OS Build CI

on:
  push:
    branches: [ "main", "new" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4.1.7

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang lld nasm mtools dosfstools gdisk exfatprogs exfat-fuse

    - name: Fix Binary Permissions
      run: |
        chmod +x binaries/limine || true

    - name: Compile OS
      run: python3 compile.py

    - name: Upload Disk Image
      uses: actions/upload-artifact@v4
      with:
        name: windoge-os-image
        path: |
          *.img
          *.iso
          *.bin